import 'package:flutter/material.dart';
import 'package:eventease/features/support/data/models/customer_request.dart';
import 'package:eventease/shared/models/event/event_category.dart';
import 'package:eventease/core/services/supabase_service.dart';
import 'package:uuid/uuid.dart';

class RequestProvider with ChangeNotifier {
  List<CustomerRequest> _requests = [];
  List<CustomerRequest> _vendorRequests = []; // Requests relevant to current vendor
  bool _isLoading = false;

  List<CustomerRequest> get requests => _requests;
  List<CustomerRequest> get vendorRequests => _vendorRequests;
  bool get isLoading => _isLoading;

  // Load requests from Supabase
  Future<void> loadRequests() async {
    _isLoading = true;
    notifyListeners();

    try {
      final response = await SupabaseService.select(table: 'customer_requests');
      print('DEBUG: loadRequests() fetched ${response.length} items from customer_requests table');
      _requests = response.map((json) => CustomerRequest.fromJson(json)).toList();
    } catch (e) {
      print('Error loading requests: $e');
      _requests = [];
    }

    _isLoading = false;
    notifyListeners();
  }

  // For customers: get their requests
  List<CustomerRequest> getCustomerRequests(String customerId) {
    return _requests.where((request) => request.customerId == customerId).toList();
  }

  // For vendors: get requests they can respond to (based on category or all)
  Future<void> loadVendorRequests(String vendorId, String vendorName) async {
    print("DEBUG: fetching all requests for vendor view...");
    
    // Always fetch fresh data first so we don't filter an empty list
    await loadRequests(); 
    
    print("DEBUG: Raw requests count from DB: ${_requests.length}");
    
    // In a real app, this would filter based on vendor's services/categories
    // For now, show all pending requests and assign vendorName for chat
    _vendorRequests = _requests.where((request) => request.status == RequestStatus.pending).toList();
    
    print("DEBUG: Filtered Pending requests for vendor: ${_vendorRequests.length}");
    if (_vendorRequests.isNotEmpty) {
      print("DEBUG: Request 1 ID: ${_vendorRequests[0].id}, Category: ${_vendorRequests[0].eventCategory.displayName}");
    }
    
    notifyListeners();
  }

  Future<void> addRequest(CustomerRequest request) async {
    try {
      final jsonData = request.toJson();
      // Remove id since it's auto-generated by the database
      jsonData.remove('id');
      // Convert customerId to UUID if needed
      jsonData['customer_id'] = request.customerId;

      final response = await SupabaseService.insert(table: 'customer_requests', data: jsonData);
      if (response.isNotEmpty) {
        final newRequest = CustomerRequest.fromJson(response.first);
        _requests.add(newRequest);
        notifyListeners();
      }
    } catch (e) {
      print('Error adding request: $e');
      // Fallback to local storage
      _requests.add(request);
      notifyListeners();
    }
  }

  Future<void> addQuickInquiry({
    required String customerId,
    required String customerName,
    required EventCategory eventCategory,
    required DateTime eventDate,
    required String vendorId,
    required String vendorName,
    String? eventType,
    double? budget,
    String? description,
    String? location,
    int? guestCount,
  }) async {
    final request = CustomerRequest(
      id: const Uuid().v4(),
      customerId: customerId,
      customerName: customerName,
      eventCategory: eventCategory,
      eventType: eventType ?? 'General Event',
      eventDate: eventDate,
      budget: budget ?? 0,
      description: description ?? 'Quick inquiry from search',
      location: location ?? '',
      guestCount: guestCount ?? 0,
      status: RequestStatus.pending,
      createdAt: DateTime.now(),
      offers: [],
    );

    await addRequest(request);
  }

  Future<void> updateRequest(String requestId, CustomerRequest updatedRequest) async {
    try {
      final jsonData = updatedRequest.toJson();
      jsonData.remove('id');
      jsonData['customer_id'] = updatedRequest.customerId;
      jsonData['updated_at'] = DateTime.now().toIso8601String();

      final response = await SupabaseService.update(
        table: 'customer_requests',
        data: jsonData,
        column: 'id',
        value: requestId,
      );

      if (response.isNotEmpty) {
        final index = _requests.indexWhere((r) => r.id == requestId);
        if (index != -1) {
          _requests[index] = CustomerRequest.fromJson(response.first);
          notifyListeners();
        }
      }
    } catch (e) {
      print('Error updating request: $e');
      // Fallback to local update
      final index = _requests.indexWhere((r) => r.id == requestId);
      if (index != -1) {
        _requests[index] = updatedRequest;
        notifyListeners();
      }
    }
  }

  Future<void> addOffer(String requestId, RequestOffer offer) async {
    final request = _requests.firstWhere((r) => r.id == requestId);
    final updatedRequest = request.copyWith(
      offers: [...request.offers, offer],
      status: RequestStatus.offered,
    );
    await updateRequest(requestId, updatedRequest);
  }

  Future<void> acceptOffer(String requestId, String offerId) async {
    final request = _requests.firstWhere((r) => r.id == requestId);
    final updatedRequest = request.copyWith(status: RequestStatus.accepted);
    await updateRequest(requestId, updatedRequest);
    // In a real app, this might trigger booking creation
  }

  Future<void> rejectOffer(String requestId) async {
    final request = _requests.firstWhere((r) => r.id == requestId);
    final updatedRequest = request.copyWith(status: RequestStatus.rejected);
    await updateRequest(requestId, updatedRequest);
  }
  Future<void> deleteRequest(String requestId) async {
    try {
      await SupabaseService.delete(
        table: 'customer_requests',
        column: 'id',
        value: requestId,
      );
      
      _requests.removeWhere((r) => r.id == requestId);
      notifyListeners();
    } catch (e) {
      print('Error deleting request: $e');
      // If offline or failed, try local remove for UI responsiveness (optional, but safer to just notify error)
      // rethrow; 
    }
  }
}
