import 'package:flutter/material.dart';
import 'package:eventease/shared/models/gift_registry.dart';

class AddEditItemDialog extends StatefulWidget {
  final GiftRegistryItem? item;

  const AddEditItemDialog({super.key, this.item});

  @override
  State<AddEditItemDialog> createState() => _AddEditItemDialogState();
}

class _AddEditItemDialogState extends State<AddEditItemDialog> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _nameController;
  late TextEditingController _descriptionController;
  late TextEditingController _priceController;
  late TextEditingController _imageUrlController;
  late TextEditingController _categoryController;
  late TextEditingController _quantityController;

  @override
  void initState() {
    super.initState();
    _nameController = TextEditingController(text: widget.item?.name ?? '');
    _descriptionController = TextEditingController(text: widget.item?.description ?? '');
    _priceController = TextEditingController(text: widget.item?.price.toString() ?? '');
    _imageUrlController = TextEditingController(text: widget.item?.imageUrl ?? '');
    _categoryController = TextEditingController(text: widget.item?.category ?? 'General');
    _quantityController = TextEditingController(text: widget.item?.quantity.toString() ?? '1');
  }

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    _priceController.dispose();
    _imageUrlController.dispose();
    _categoryController.dispose();
    _quantityController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // Generate a temporary ID if new
    // Note: In real app, ID usually generated by DB or Service, 
    // but here we might need it for the model construction before sending.
    // For update, use existing ID.
    // For create, we can assign a temp one or let the provider handle it (provider uses Supabase gen_random_uuid usually).
    // Let's assume we return a GiftRegistryItem with a potentially temp ID or null ID if we made it nullable (it's not).
    // We'll use a placeholder for new items.
    
    return AlertDialog(
      title: Text(widget.item == null ? 'Add Item' : 'Edit Item'),
      content: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Item Name'),
                validator: (value) => value == null || value.isEmpty ? 'Please enter a name' : null,
              ),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(labelText: 'Description'),
                maxLines: 2,
              ),
              Row(
                children: [
                   Expanded(
                    child: TextFormField(
                      controller: _priceController,
                      decoration: const InputDecoration(labelText: 'Price', prefixText: 'RM '),
                      keyboardType: const TextInputType.numberWithOptions(decimal: true),
                      validator: (value) {
                         if (value == null || value.isEmpty) return 'Enter price';
                         if (double.tryParse(value) == null) return 'Invalid price';
                         return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextFormField(
                      controller: _quantityController,
                      decoration: const InputDecoration(labelText: 'Quantity'),
                      keyboardType: TextInputType.number,
                       validator: (value) {
                         if (value == null || value.isEmpty) return 'Enter qty';
                         if (int.tryParse(value) == null) return 'Invalid qty';
                         return null;
                      },
                    ),
                  ),
                ],
              ),
              TextFormField(
                controller: _categoryController,
                decoration: const InputDecoration(labelText: 'Category'),
              ),
              TextFormField(
                controller: _imageUrlController,
                decoration: const InputDecoration(labelText: 'Image URL (Optional)'),
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: () {
            if (_formKey.currentState!.validate()) {
              final newItem = GiftRegistryItem(
                id: widget.item?.id ?? '', // ID handled by Provider/DB usually, passing empty for new
                name: _nameController.text,
                description: _descriptionController.text,
                price: double.parse(_priceController.text),
                imageUrl: _imageUrlController.text.isNotEmpty ? _imageUrlController.text : null,
                category: _categoryController.text,
                quantity: int.parse(_quantityController.text),
                remainingQuantity: int.parse(_quantityController.text), // Reset remaining if editing? Or handle logic. For new, matches quantity.
                isPurchased: false,
              );
              Navigator.pop(context, newItem);
            }
          },
          child: const Text('Save'),
        ),
      ],
    );
  }
}
