// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH8jdpuyZ7cs5LqvRAnbznPv9KDxWlYps',
    appId: '1:576075181196:web:9f43885806cdbe326fdfa9',
    messagingSenderId: '576075181196',
    projectId: 'eventease-5def8',
    authDomain: 'eventease-5def8.firebaseapp.com',
    storageBucket: 'eventease-5def8.firebasestorage.app',
    measurementId: 'G-TE02EPR91H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrsm2S_TTPRB6FMb4DNi4LqJ51snmufSU',
    appId: '1:576075181196:android:affff99de7c61dd26fdfa9',
    messagingSenderId: '576075181196',
    projectId: 'eventease-5def8',
    storageBucket: 'eventease-5def8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLCtzH6YVvIwWciKlfrYvI2DMHQXbxXu0',
    appId: '1:576075181196:ios:8eeba65edf8aec436fdfa9',
    messagingSenderId: '576075181196',
    projectId: 'eventease-5def8',
    storageBucket: 'eventease-5def8.firebasestorage.app',
    iosBundleId: 'com.example.eventeaseNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLCtzH6YVvIwWciKlfrYvI2DMHQXbxXu0',
    appId: '1:576075181196:ios:8eeba65edf8aec436fdfa9',
    messagingSenderId: '576075181196',
    projectId: 'eventease-5def8',
    storageBucket: 'eventease-5def8.firebasestorage.app',
    iosBundleId: 'com.example.eventeaseNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH8jdpuyZ7cs5LqvRAnbznPv9KDxWlYps',
    appId: '1:576075181196:web:2165434c8c5830eb6fdfa9',
    messagingSenderId: '576075181196',
    projectId: 'eventease-5def8',
    authDomain: 'eventease-5def8.firebaseapp.com',
    storageBucket: 'eventease-5def8.firebasestorage.app',
    measurementId: 'G-G0XPE7JS77',
  );
}
